# 热部署
spring:
    devtools:
        restart:
            enabled: true
            additional-exclude: WEB-INF/**
    # 配置静态资源文件路径
    mvc:
        static-path-pattern: /static/**
#    resources:
#        static-locations: ["/templates/","/resources/","/static/","/public/"]
    # 配置数据库连接
#    datasource:
#        url: jdbc:mysql://localhost:3306/sakila?useUnicode=true&characterEncoding=utf-8&useSSL=false
#        username: root
#        password:
#        driver-class-name: com.mysql.jdbc.Driver

    # redis配置
#    redis:
#        database: 0
#        host: localhost
#        port: 6379
#        password:
#        pool:
#            max-active: 8
#            max-wait: -1
#            max-idle: 8
#            min-idle: 0
#        timeout: 0
    # 配置模版引擎
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        cache: false


# 配置端口号
server:
    port: 8081

# 配置mybatis
#mybatis:
#    mapper-locations: classpath:mappers/*.xml